import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const recoleta = localFont({
  src: [
    {
      path: "../../public/fonts/Recoleta-RegularDEMO.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-recoleta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${recoleta.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
